from pydantic import BaseModel
from sqlalchemy.engine import Engine
from sqlmodel import Field, Session, SQLModel


class Room(SQLModel, table=True):
    # Primary Key: Auto-generated by database (usually)
    id: int | None = Field(default=None, primary_key=True)

    # Name of the room (e.g., "Cozy Single Room")
    name: str = Field(max_length=100, index=True)

    # Price per night (Float is standard for simple examples, Decimal for finance apps)
    price_per_night: float = Field(default=0.0)

    # Number of bedrooms
    bedrooms: int = Field(ge=0)  # Greater than or equal to 0

    # Number of bathrooms
    bathroom: int = Field(ge=0)  # Greater than or equal to 0

    # Area in square meters (or feet)
    area: float = Field(gt=0.0)  # Greater than 0


class RoomCreate(BaseModel):
    name: str = Field(min_length=1, max_length=100)
    price_per_night: float = Field(ge=0)
    bedrooms: int = Field(ge=0)
    bathroom: int = Field(ge=0)
    area: float = Field(gt=0)


class RoomUpdate(SQLModel):
    price_per_night: float = Field(ge=0)
